### ISSUE TITLE
Running code as-is throws error

### ISSUE THREAD

**Issue by LuckyDao** [adobe-apiplatform/umapi-documentation#30]
Error:
Traceback (most recent call last):
  File "C:\Python36\lib\configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'server'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Python36/Env/JWTConnection/JWTConnection.py", line 27, in <module>
    ims_host = config.get("server", "ims_host")
  File "C:\Python36\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Python36\lib\configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'server'
PyDev console: starting.

Running windows 10, python 3.6

**Comment by lesavage** [comment]
`configparser.NoSectionError: No section: 'server'` was the config file properly populated?
